jongrate/jongrate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rate.urls')),
]

jongrate/rate/urls.py
from django.urls import path
from . import views

app_name = 'rate'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('data/', views.Data.as_view(), name='data'),
    path('rate/', views.Rate.as_view(), name='rate'),
    path('settings/', views.Settings.as_view(), name='settings'),
]

jongrate/rate/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class GameMode(models.Model):
    """
    対局モードを表す。
    - name: 「東風戦」「半荘戦」など
    """
    name = models.CharField(max_length=20)


class GameInfo(models.Model):
    """
    対局情報を表す。
    - dt: 対局日時
    - mode: 対局モード
    """
    dt = models.DateTimeField()
    mode = models.ForeignKey(GameMode, on_delete=models.PROTECT)


class Player(models.Model):
    """
    プレイヤー情報を表す。
    - name: プレイヤー名
    """
    name = models.CharField(max_length=20)


class GameResult(models.Model):
    """
    対局結果を表す。
    - game: 対局情報
    - player: プレイヤー
    - score: playerがこの対局で得た点数
    - rank: playerのこの対局における順位
    """
    game = models.ForeignKey(GameInfo, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.PROTECT)
    score = models.IntegerField()
    rank = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(4)])

jongrate/rate/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.conf import settings
# from django.utils.timezone import make_aware
import datetime
import copy
import math
import pandas as pd
# from pandas.errors import ValueError
from pytz import timezone
from rate.models import Player, GameInfo, GameResult, GameMode


class Index(View):
    def get(self, request):
        context = {}
        return render(request, 'rate/index.html', context)


class Data(View):
    def get(self, request):
        player_list = [p.name for p in Player.objects.all()]
        gamemode_list = [g.name for g in GameMode.objects.all()]

        # gr_raw = GameResult.objects.all()
        # gr_list = []
        # for gr in gr_raw:

        #     gr_dict = {
        #         'game_dt': gr.game.dt,
        #     }
        #     gr_list.append(gr_dict)

        gi_raw_list = GameInfo.objects.all().order_by('-dt', '-pk')
        gr_list = []
        for gi in gi_raw_list:
            gr = GameResult.objects.filter(game=gi).order_by('rank')
            gr_dict = {
                'game_dt': gi.dt,
                'game_mode': gi.mode.name,
            }

            for i in range(len(gr)):
                gr_dict[f'rank{i+1}'] = gr[i].player.name + \
                    '：' + str(gr[i].score)

            gr_list.append(gr_dict)

        context = {
            'player_list': player_list,
            'gm_list': gamemode_list,
            'gr_list': gr_list,
        }
        return render(request, 'rate/data.html', context)

    def post(self, request):

        # 対局情報の保存
        gm = GameMode.objects.get(name=request.POST['gamemode'])
        naive_dt = datetime.datetime.fromisoformat(request.POST['datetime'])
        aware_dt = naive_dt.replace(tzinfo=timezone(settings.TIME_ZONE))
        gi = GameInfo.objects.create(dt=aware_dt, mode=gm)

        # 対局結果の保存
        for i in range(4):
            GameResult.objects.create(
                game=gi,
                player=Player.objects.get(name=request.POST[f'player{i+1}']),
                score=request.POST[f'score{i+1}'],
                rank=request.POST[f'rank{i+1}']
            )

        context = {}
        return redirect(reverse('rate:data'), context)


class Rate(View):
    def get(self, request):

        rate_list = self.mori_calc_rate()
        player_list = [p.name for p in Player.objects.all()]

        labels = [''] * len(rate_list[0])
        datasets = []
        for i in range(len(player_list)):
            color = 'rgb(255, 99, 132)'
            data = {
                'label': player_list[i],
                'backgroundColor': color,
                'borderColor': color,
                'data': rate_list[i]
            }
            datasets.append(data)

        graph_data = {
            'labels': labels,
            'datasets': datasets
        }

        context = {
            'graph_data': graph_data
        }
        return render(request, 'rate/rate.html', context)

    def mori_calc_rate(self):

        player_list = [p.name for p in Player.objects.all()]

        # 順位表の初期化
        rank_df = pd.DataFrame(columns=player_list)

        info_list = GameInfo.objects.all().order_by('dt', 'pk')
        for info in info_list:

            # ある対局での4人の対局結果情報を取得する
            res_list = GameResult.objects.filter(game=info)
            res_player = [res.player.name for res in res_list]
            res_rank = [res.rank for res in res_list]

            s = pd.DataFrame([res_rank], columns=res_player)
            rank_df = pd.concat([rank_df, s], ignore_index=True)

        # レート表の初期化
        # レートの初期値は1000
        rate_df = pd.DataFrame(index=[0], columns=player_list)
        rate_df.fillna(1000, inplace=True)

        # 高速化のために辞書型に変換
        rank_dict = rank_df.to_dict('records')

        for rank in rank_dict:
            rate = [''] * len(player_list)
            for i, k1 in enumerate(rank):
                for j, k2 in enumerate(rank):
                    if i >= j or math.isnan(rank[k1]) or math.isnan(rank[k2]):
                        continue

        # for game_num in range(len(rank_list[0])):

        #     for p1 in range(len(player_list)):
        #         # print(p1)
        #         # print('rate_list')
        #         # print(rate_list)
        #         # print('')

        #         # この局(game_num)に参加していないプレイヤーのレートは変動しない
        #         if rank_list[p1][game_num] == 0:
        #             # print(p1)
        #             # print(rate_list)
        #             prev_rate = rate_list[p1][game_num]
        #             rate_list[p1].append(copy.deepcopy(prev_rate))
        #             # print(rate_list[p1])
        #             # print('')
        #             continue

        #         print('rate_list (if suru-)')
        #         print(rate_list)
        #         print('')

        #         # 上の処理を全員に対して行うためにわざと1回多くループを回してる
        #         # このbreakが無いと、下のforで配列外参照が起きる
        #         if p1 == (len(player_list) - 1):
        #             break

        #         for p2 in range(p1 + 1, len(player_list)):

        #             if rank_list[p2][game_num] == 0:
        #                 continue

        #             p1_rate = rate_list[p1][-1]
        #             p2_rate = rate_list[p2][-1]

        #             w = p2_rate / p1_rate
        #             w = 2 if w > 2 else w
        #             w = 0.5 if w < 0.5 else w

        #             new_p1_rate = p1_rate + int(30 * w)
        #             new_p2_rate = p2_rate - int(30 * w)

        #             if rank_list[p1][game_num] < rank_list[p2][game_num]:
        #                 new_p1_rate = p1_rate - int(30 * w)
        #                 new_p2_rate = p2_rate + int(30 * w)

        #             rate_list[p1].append(new_p1_rate)
        #             rate_list[p2].append(new_p2_rate)

        # print(rate_list)
        # return rate_list
        return


class Settings(View):
    def get(self, request):
        context = {}
        return render(request, 'rate/settings.html', context)

    def post(self, request):
        new_player = request.POST.get('new-player', False)
        new_gm = request.POST.get('new-gm', False)

        if new_player:
            Player.objects.create(name=new_player)

        if new_gm:
            GameMode.objects.create(name=new_gm)

        context = {}
        return render(request, 'rate/settings.html', context)

jongrate/rate/templates/rate/data.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>麻雀友人戦レーティングシステム</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>

    <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
            <a href="{% url 'rate:index' %}"
                class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
                <span class="fs-4">麻雀友人戦レーティングシステム</span>
            </a>

            <ul class="nav nav-pills">
                <li class="nav-item"><a href="{% url 'rate:index' %}" class="nav-link">ホーム</a></li>
                <li class="nav-item"><a href="{% url 'rate:data' %}" class="nav-link active">対局結果</a></li>
                <li class="nav-item"><a href="{% url 'rate:rate' %}" class="nav-link">レート</a></li>
            </ul>
        </header>
    </div>

    <div class="container">

        <h2>対局データの追加</h2>

        <form action="{% url 'rate:data' %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="datetime" class="form-label">対局日時</label>
                <input type="datetime-local" class="form-control" id="datetime" name="datetime" required>
            </div>
            <div class="mb-3">
                <label for="gamemode" class="form-label">ゲームモード</label>
                <select class="form-select" id="gamemode" name="gamemode" required>
                    <option disabled selected value="">ゲームモードを選択する</option>
                    {% for gm in gm_list %}
                        <option value="{{ gm }}">{{ gm }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="row">
                {% with ''|center:4 as range4 %}
                {% for _ in range4 %}
                    <div class="col-3">
                        <div class="mb-3">
                            <label for="player{{ forloop.counter }}" class="form-label">プレイヤー{{ forloop.counter }}</label>
                            <select class="form-select" id="player{{ forloop.counter }}" name="player{{ forloop.counter }}" required>
                                <option disabled selected value="">プレイヤーを選択する</option>
                                {% for player in player_list %}
                                    <option value="{{ player }}">{{ player }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="score{{ forloop.counter }}" class="form-label">スコア</label>
                            <input type="number" class="form-control" id="score{{ forloop.counter }}" name="score{{ forloop.counter }}" value="25000" step="100" required>
                        </div>
                        <div class="mb-3">
                            <label for="rank{{ forloop.counter }}" class="form-label">順位</label>
                            <select class="form-select" id="rank{{ forloop.counter }}" name="rank{{ forloop.counter }}" required>
                                <option disabled selected value="">順位を選択する</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                        </div>
                    </div>
                {% endfor %}
                {% endwith %}
            </div>
            <button type="submit" class="btn btn-primary">追加</button>
        </form>

    </div>

    <div class="container">

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">対局日時</th>
                    <th scope="col">ゲームモード</th>
                    <th scope="col">1位</th>
                    <th scope="col">2位</th>
                    <th scope="col">3位</th>
                    <th scope="col">4位</th>
                </tr>
            </thead>
            <tbody>
                {% for gr in gr_list %}
                    <tr>
                        <td>{{ gr.game_dt }}</td>
                        <td>{{ gr.game_mode }}</td>
                        <td>{{ gr.rank1 }}</td>
                        <td>{{ gr.rank2 }}</td>
                        <td>{{ gr.rank3 }}</td>
                        <td>{{ gr.rank4 }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

jongrate/rate/templates/rate/index.html
heloo!

jongrate/rate/templates/rate/rate.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>麻雀友人戦レーティングシステム</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
            <a href="{% url 'rate:index' %}"
                class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
                <span class="fs-4">麻雀友人戦レーティングシステム</span>
            </a>

            <ul class="nav nav-pills">
                <li class="nav-item"><a href="{% url 'rate:index' %}" class="nav-link">ホーム</a></li>
                <li class="nav-item"><a href="{% url 'rate:data' %}" class="nav-link">対局結果</a></li>
                <li class="nav-item"><a href="{% url 'rate:rate' %}" class="nav-link active">レート</a></li>
            </ul>
        </header>
    </div>


    <div class="container">
        <canvas class="my-4" id="chart">
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.2/chart.min.js"
        integrity="sha512-zjlf0U0eJmSo1Le4/zcZI51ks5SjuQXkU0yOdsOBubjSmio9iCUp8XPLkEAADZNBdR9crRy3cniZ65LF2w8sRA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        {% autoescape off %}
        const data = {{ graph_data }};
        {% endautoescape %}
    </script>
    <script src="{% static 'rate/graph.js' %}"></script>
</body>

</html>

jongrate/rate/templates/rate/settings.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>麻雀友人戦レーティングシステム</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>

    <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
            <a href="{% url 'rate:index' %}"
                class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
                <span class="fs-4">麻雀友人戦レーティングシステム</span>
            </a>

            <ul class="nav nav-pills">
                <li class="nav-item"><a href="{% url 'rate:index' %}" class="nav-link">ホーム</a></li>
                <li class="nav-item"><a href="{% url 'rate:data' %}" class="nav-link active">対局結果</a></li>
                <li class="nav-item"><a href="{% url 'rate:rate' %}" class="nav-link">レート</a></li>
            </ul>
        </header>
    </div>


    <div class="container">
        <h2>プレイヤーの追加</h2>
        <form action="{% url 'rate:settings' %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="new-player" class="form-label">プレイヤー名</label>
                <input type="text" class="form-control" name="new-player" id="new-player" required>
            </div>
            <button type="submit" class="btn btn-primary">追加</button>
        </form>
    </div>

    <div class="container">
        <h2>ゲームモードの追加</h2>
        <form action="{% url 'rate:settings' %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="new-gm" class="form-label">ゲームモード名</label>
                <input type="text" class="form-control" name="new-gm" id="new-gm" required>
            </div>
            <button type="submit" class="btn btn-primary">追加</button>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>